"""Unit tests for lightweight landmark detection and grounded story generation."""

import unittest
from pathlib import Path
import numpy as np
import cv2

from app.vision.landmark_detector import LandmarkDetector
from app.vision.landmark_service import LandmarkStoryService
from app.vision.place_content import content_for_label


class MockLLM:
    def __init__(self, response_text="A vibrant story generated by mock LLM."):
        self.response_text = response_text
        self.call_count = 0

    def chat(self, messages, **_kwargs):
        self.call_count += 1
        return self.response_text


class FailingLLM:
    def chat(self, *args, **kwargs):
        raise ConnectionError("LLM server offline")


class VisionLandmarkTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.backend_dir = Path(__file__).resolve().parents[1]
        cls.model_path = cls.backend_dir / "models" / "landmark_orb_index.npz"
        cls.dataset_dir = cls.backend_dir / "dataset"

        if not cls.model_path.exists():
            LandmarkDetector.train(cls.dataset_dir, cls.model_path)

        cls.detector = LandmarkDetector(cls.model_path)

    def test_place_content_retrieval(self):
        ima = content_for_label("ima_keithel")
        self.assertIsNotNone(ima)
        self.assertEqual(ima.place_id, "ima_keithel")
        self.assertTrue(len(ima.facts) >= 3)
        self.assertTrue(len(ima.highlights) >= 2)
        self.assertIn("Nupi Lan", ima.fallback_story)

        kangla = content_for_label("Kangla")
        self.assertIsNotNone(kangla)
        self.assertEqual(kangla.place_id, "kangla")
        self.assertTrue(len(kangla.facts) >= 3)
        self.assertIn("Kangla Sha", kangla.fallback_story)

    def test_ima_keithel_detection(self):
        ima_files = list((self.dataset_dir / "Ima Keithel").glob("*.jpg"))
        self.assertTrue(len(ima_files) > 0, "No Ima Keithel dataset images found")

        sample_img = ima_files[0].read_bytes()
        detection = self.detector.detect(sample_img)

        self.assertEqual(detection.label, "ima_keithel")
        self.assertGreater(detection.confidence, 0.70)
        self.assertGreater(detection.good_matches, 20)

    def test_kangla_detection(self):
        kangla_files = list((self.dataset_dir / "Kangla").glob("*.jpeg")) + list(
            (self.dataset_dir / "Kangla").glob("*.jpg")
        )
        self.assertTrue(len(kangla_files) > 0, "No Kangla dataset images found")

        sample_img = kangla_files[0].read_bytes()
        detection = self.detector.detect(sample_img)

        self.assertEqual(detection.label, "kangla")
        self.assertGreater(detection.confidence, 0.70)
        self.assertGreater(detection.good_matches, 20)

    def test_unrelated_noise_rejection(self):
        # Generate random uniform RGB noise
        noise = np.random.randint(0, 255, (300, 300, 3), dtype=np.uint8)
        _, encoded = cv2.imencode(".jpg", noise)
        detection = self.detector.detect(encoded.tobytes())

        self.assertIsNone(detection.label)

    def test_story_service_with_mock_llm(self):
        mock_llm = MockLLM("Under the morning sky of Imphal, Ima Keithel awakes.")
        service = LandmarkStoryService(detector=self.detector, llm=mock_llm)

        ima_files = list((self.dataset_dir / "Ima Keithel").glob("*.jpg"))
        result = service.recognize(ima_files[0].read_bytes())

        self.assertTrue(result.recognized)
        self.assertEqual(result.place_id, "ima_keithel")
        self.assertEqual(result.name, "Ima Keithel")
        self.assertEqual(result.story, "Under the morning sky of Imphal, Ima Keithel awakes.")
        self.assertTrue(result.llm_generated)
        self.assertTrue(len(result.facts) >= 3)
        self.assertEqual(mock_llm.call_count, 1)

    def test_story_service_fallback_when_llm_offline(self):
        failing_llm = FailingLLM()
        service = LandmarkStoryService(detector=self.detector, llm=failing_llm)

        ima_files = list((self.dataset_dir / "Ima Keithel").glob("*.jpg"))
        result = service.recognize(ima_files[0].read_bytes())

        self.assertTrue(result.recognized)
        self.assertEqual(result.place_id, "ima_keithel")
        self.assertFalse(result.llm_generated)
        self.assertIn("Ima Keithel", result.story)
        self.assertTrue(len(result.facts) >= 3)

    def test_grpc_recognize_landmark(self):
        import grpc
        from concurrent import futures
        from app.grpc.generated import meerup_pb2, meerup_pb2_grpc
        from app.grpc.server import MeerupAIServicer

        mock_llm = MockLLM("A gRPC story test.")
        service = LandmarkStoryService(detector=self.detector, llm=mock_llm)
        server = grpc.server(futures.ThreadPoolExecutor(max_workers=1))
        meerup_pb2_grpc.add_MeerupAIServicer_to_server(
            MeerupAIServicer(vision_service=service), server
        )
        port = server.add_insecure_port("127.0.0.1:0")
        server.start()

        channel = grpc.insecure_channel(f"127.0.0.1:{port}")
        try:
            stub = meerup_pb2_grpc.MeerupAIStub(channel)
            sample_img = list((self.dataset_dir / "Ima Keithel").glob("*.jpg"))[0].read_bytes()
            resp = stub.RecognizeLandmark(meerup_pb2.LandmarkPhotoRequest(image_data=sample_img))
            self.assertTrue(resp.recognized)
            self.assertEqual(resp.place_id, "ima_keithel")
            self.assertEqual(resp.name, "Ima Keithel")
            self.assertGreater(resp.confidence, 0.70)
            self.assertEqual(resp.story, "A gRPC story test.")
        finally:
            channel.close()
            server.stop(grace=0).wait()


if __name__ == "__main__":
    unittest.main()

