# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/sts.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/sts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproto/sts.proto\x12\x03sts\"\x8f\x01\n\x18SpeechTranslationRequest\x12\x15\n\raudio_content\x18\x01 \x01(\x0c\x12\x14\n\x0c\x61udio_format\x18\x02 \x01(\t\x12\x17\n\x0fsource_language\x18\x03 \x01(\t\x12\x17\n\x0ftarget_language\x18\x04 \x01(\t\x12\x14\n\x0cvoice_gender\x18\x05 \x01(\t\"\x8e\x01\n\x19SpeechTranslationResponse\x12\x17\n\x0frecognized_text\x18\x01 \x01(\t\x12\x17\n\x0ftranslated_text\x18\x02 \x01(\t\x12\x15\n\raudio_content\x18\x03 \x01(\x0c\x12\x14\n\x0c\x61udio_format\x18\x04 \x01(\t\x12\x12\n\nlatency_ms\x18\x05 \x01(\x03\"n\n\x16TextTranslationRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x17\n\x0fsource_language\x18\x02 \x01(\t\x12\x17\n\x0ftarget_language\x18\x03 \x01(\t\x12\x14\n\x0cvoice_gender\x18\x04 \x01(\t\"\x8a\x01\n\x17TextTranslationResponse\x12\x15\n\roriginal_text\x18\x01 \x01(\t\x12\x17\n\x0ftranslated_text\x18\x02 \x01(\t\x12\x15\n\raudio_content\x18\x03 \x01(\x0c\x12\x14\n\x0c\x61udio_format\x18\x04 \x01(\t\x12\x12\n\nlatency_ms\x18\x05 \x01(\x03\"\x14\n\x12HealthCheckRequest\"B\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x1b\n\x13\x62hashini_configured\x18\x02 \x01(\x08\x32\xfa\x01\n\x18SpeechTranslationService\x12P\n\x0fTranslateSpeech\x12\x1d.sts.SpeechTranslationRequest\x1a\x1e.sts.SpeechTranslationResponse\x12J\n\rTranslateText\x12\x1b.sts.TextTranslationRequest\x1a\x1c.sts.TextTranslationResponse\x12@\n\x0b\x43heckHealth\x12\x17.sts.HealthCheckRequest\x1a\x18.sts.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.sts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SPEECHTRANSLATIONREQUEST']._serialized_start=25
  _globals['_SPEECHTRANSLATIONREQUEST']._serialized_end=168
  _globals['_SPEECHTRANSLATIONRESPONSE']._serialized_start=171
  _globals['_SPEECHTRANSLATIONRESPONSE']._serialized_end=313
  _globals['_TEXTTRANSLATIONREQUEST']._serialized_start=315
  _globals['_TEXTTRANSLATIONREQUEST']._serialized_end=425
  _globals['_TEXTTRANSLATIONRESPONSE']._serialized_start=428
  _globals['_TEXTTRANSLATIONRESPONSE']._serialized_end=566
  _globals['_HEALTHCHECKREQUEST']._serialized_start=568
  _globals['_HEALTHCHECKREQUEST']._serialized_end=588
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=590
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=656
  _globals['_SPEECHTRANSLATIONSERVICE']._serialized_start=659
  _globals['_SPEECHTRANSLATIONSERVICE']._serialized_end=909
# @@protoc_insertion_point(module_scope)
