# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import sts_pb2 as proto_dot_sts__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/sts_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SpeechTranslationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TranslateSpeech = channel.unary_unary(
                '/sts.SpeechTranslationService/TranslateSpeech',
                request_serializer=proto_dot_sts__pb2.SpeechTranslationRequest.SerializeToString,
                response_deserializer=proto_dot_sts__pb2.SpeechTranslationResponse.FromString,
                _registered_method=True)
        self.TranslateText = channel.unary_unary(
                '/sts.SpeechTranslationService/TranslateText',
                request_serializer=proto_dot_sts__pb2.TextTranslationRequest.SerializeToString,
                response_deserializer=proto_dot_sts__pb2.TextTranslationResponse.FromString,
                _registered_method=True)
        self.CheckHealth = channel.unary_unary(
                '/sts.SpeechTranslationService/CheckHealth',
                request_serializer=proto_dot_sts__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=proto_dot_sts__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class SpeechTranslationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TranslateSpeech(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TranslateText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpeechTranslationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TranslateSpeech': grpc.unary_unary_rpc_method_handler(
                    servicer.TranslateSpeech,
                    request_deserializer=proto_dot_sts__pb2.SpeechTranslationRequest.FromString,
                    response_serializer=proto_dot_sts__pb2.SpeechTranslationResponse.SerializeToString,
            ),
            'TranslateText': grpc.unary_unary_rpc_method_handler(
                    servicer.TranslateText,
                    request_deserializer=proto_dot_sts__pb2.TextTranslationRequest.FromString,
                    response_serializer=proto_dot_sts__pb2.TextTranslationResponse.SerializeToString,
            ),
            'CheckHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckHealth,
                    request_deserializer=proto_dot_sts__pb2.HealthCheckRequest.FromString,
                    response_serializer=proto_dot_sts__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sts.SpeechTranslationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sts.SpeechTranslationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SpeechTranslationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TranslateSpeech(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sts.SpeechTranslationService/TranslateSpeech',
            proto_dot_sts__pb2.SpeechTranslationRequest.SerializeToString,
            proto_dot_sts__pb2.SpeechTranslationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TranslateText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sts.SpeechTranslationService/TranslateText',
            proto_dot_sts__pb2.TextTranslationRequest.SerializeToString,
            proto_dot_sts__pb2.TextTranslationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sts.SpeechTranslationService/CheckHealth',
            proto_dot_sts__pb2.HealthCheckRequest.SerializeToString,
            proto_dot_sts__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
